# Generated by Django 5.0.6 on 2024-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kouty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
