# Generated by Django 5.1 on 2024-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kouty", "0002_partenaire_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("source", models.CharField(max_length=200)),
                ("lien", models.URLField(blank=True, max_length=500, null=True)),
                ("extrait", models.TextField()),
                ("date_publication", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Temoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Client", "Client"),
                            ("Employé", "Employé"),
                            ("Partenaire", "Partenaire"),
                            ("Fournisseur", "Fournisseur"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=100,
                    ),
                ),
                ("temoignage", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="Temoignages/"),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
