# Generated by Django 5.1 on 2024-08-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kouty", "0003_mention_temoin"),
    ]

    operations = [
        migrations.AddField(
            model_name="mention",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="actualites/"),
        ),
    ]
